# config
set-option -g prefix C-t
set -g default-terminal "screen-256color"
set -g status-keys vi
setw -g mode-keys vi
set -g status-style bg=default,fg=cyan
set-option -g history-limit 100000
set -g mouse on

# prefix
unbind C-b
bind C-t send-prefix

# keybinds
bind -n M-w new-window
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
bind -n M-p previous-window
bind -n M-n next-window

bind -n M-S-Left  resize-pane -L 5
bind -n M-S-Right resize-pane -R 5
bind -n M-S-Up    resize-pane -U 3
bind -n M-S-Down  resize-pane -D 3

bind -n M-'\' split-window -h
bind -n M-'-' split-window -v
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel
bind-key -T copy-mode-vi 'V' send -X select-line
bind-key -T copy-mode-vi 'C-v' send -X rectangle-toggle

bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel "pbcopy"
